# Generated by Django 6.1.1 on 2026-09-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Opção", "verbose_name_plural": "Opções"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Questão", "verbose_name_plural": "Questões"},
        ),
    ]
